### PR TITLE
Monteway2 CinemaHall

### PR DESCRIPTION
**Pull request by agusiol**
I have a UseCase  GenerateSeats for CinemaHall and now I'm calling it in controller. I would like call it in UseCase Create, but I'm having trouble implementing it.

### CODE REVIEW

**Comment by agusiol** [comment]
@wmaciejak  I tried
 `CinemaHalls::UseCases::GenerateSeats.new(params[:cinema_hall][:capacity]).call
`
and it gives "#<NoMethodError: undefined method `[]' for nil:NilClass>"

`CinemaHalls::UseCases::GenerateSeats.new(params[:capacity]).call 
`
and I receive "#<NoMethodError: undefined method `/' for \"100\":String>" 

I didn't catch what the reason could be but I will look further :)

**Comment by wmaciejak** [comment]
Quite strange. Will check it in 30 minutes 👍

**Comment by wmaciejak** [comment]
> and I receive "#<NoMethodError: undefined method `/' for "100":String>"



It might be an issue that you probably sending `capacity` as a string. Could you try to cast this value to integert - `params[:capacity].to_i` ?

**Comment by agusiol** [comment]
> It might be an issue that you probably sending `capacity` as a string. Could you try to cast this value to integert - `params[:capacity].to_i` ?

Ekstra! Działa. Wrzuciłam całość :)

**Comment by wmaciejak** [comment]
Looks cool 👍 Good job ❤️

**Pull request merged**
